package com.example.model

data class AppItem(
    val id: String = "",
    val name: String = "",
    val packageName: String = "",
    val developer: String = "",
    val category: String = "",
    val categoryId: String = "",
    val iconUrl: String = "",
    val localIconRes: Int? = null,
    val bannerUrl: String = "",
    val localBannerRes: Int? = null,
    val rating: Float = 4.5f,
    val ratingCount: String = "1.2M",
    val downloadsCount: String = "1.2B",
    val fileSize: String = "58 MB",
    val version: String = "v1.0.0",
    val versionCode: Int = 1,
    val description: String = "",
    val screenshots: List<String> = emptyList(),
    val localScreenshotsRes: List<Int> = emptyList(),
    val tags: List<String> = emptyList(),
    val apkDownloadUrl: String = "",
    val isGame: Boolean = false,
    val isFeatured: Boolean = false,
    val isMostDownloaded: Boolean = false,
    val isUpdateAvailable: Boolean = false,
    val newVersion: String = "",
    val releaseDate: String = "2024-01-01",
    val updatedDate: String = "2024-05-10",
    val isPublished: Boolean = true,
    val isOpenSource: Boolean = false,
    val rootCompatibility: String = "No root required", // "Root required", "Root optional", "Shizuku required", "ADB required", "No root required"
    val modInfo: String = "",
    val minSdk: Int = 24,
    val targetSdk: Int = 34,
    val abi: String = "Universal",
    val uploadedApkLocalPath: String = "",
    val apkFileName: String = ""
)
